// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WSEA.Data.WSEA;

public partial class Commerce
{
    public int IdCommerce { get; set; }

    public double SquareObject { get; set; }

    public double? SquareArea { get; set; }

    public int? Floor { get; set; }

    public int? FloorCount { get; set; }

    public int IdMaterial { get; set; }

    public int IdCommerceType { get; set; }

    public virtual CommerceType IdCommerceTypeNavigation { get; set; }

    public virtual Material IdMaterialNavigation { get; set; }

    public virtual ICollection<Realty> Realties { get; set; } = new List<Realty>();
}