// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WSEA.Data.WSEA;

public partial class CommerceType
{
    public int IdCommerceType { get; set; }

    public string Name { get; set; }

    public virtual ICollection<Commerce> Commerces { get; set; } = new List<Commerce>();
}