// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WSEA.Data.WSEA;

public partial class FlatRoom
{
    public int IdFlatRoom { get; set; }

    public double? SquareObject { get; set; }

    public double SquareLiving { get; set; }

    public double? SquareKitchen { get; set; }

    public int RoomCount { get; set; }

    public int Floor { get; set; }

    public int FloorCount { get; set; }

    public bool Balcony { get; set; }

    public bool Loggia { get; set; }

    public bool Elevator { get; set; }

    public bool SecOrNew { get; set; }

    public bool FlatOrRoom { get; set; }

    public int YearBuild { get; set; }

    public int IdSanitary { get; set; }

    public int IdHeating { get; set; }

    public int IdMaterial { get; set; }

    public virtual Heating IdHeatingNavigation { get; set; }

    public virtual Material IdMaterialNavigation { get; set; }

    public virtual Sanitary IdSanitaryNavigation { get; set; }

    public virtual ICollection<Realty> Realties { get; set; } = new List<Realty>();
}