// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WSEA.Data.WSEA;

public partial class House
{
    public int IdHouse { get; set; }

    public double SquareObject { get; set; }

    public double SquareLiving { get; set; }

    public double SquareKitchen { get; set; }

    public double SquareArea { get; set; }

    public int RoomCount { get; set; }

    public int FloorCount { get; set; }

    public bool Gas { get; set; }

    public int YearBuild { get; set; }

    public int IdSanitary { get; set; }

    public int IdHeating { get; set; }

    public int IdMaterial { get; set; }

    public int IdWater { get; set; }

    public int IdCanal { get; set; }

    public int IdHouseType { get; set; }

    public virtual Canal IdCanalNavigation { get; set; }

    public virtual Heating IdHeatingNavigation { get; set; }

    public virtual HouseType IdHouseTypeNavigation { get; set; }

    public virtual Material IdMaterialNavigation { get; set; }

    public virtual Sanitary IdSanitaryNavigation { get; set; }

    public virtual Water IdWaterNavigation { get; set; }

    public virtual ICollection<Realty> Realties { get; set; } = new List<Realty>();
}