// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WSEA.Data.WSEA;

public partial class LandplotType
{
    public int IdLandplotType { get; set; }

    public string Name { get; set; }

    public virtual ICollection<Landplot> Landplots { get; set; } = new List<Landplot>();
}