// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WSEA.Data.WSEA;

public partial class Material
{
    public int IdMaterial { get; set; }

    public string Name { get; set; }

    public virtual ICollection<Commerce> Commerces { get; set; } = new List<Commerce>();

    public virtual ICollection<FlatRoom> FlatRooms { get; set; } = new List<FlatRoom>();

    public virtual ICollection<House> Houses { get; set; } = new List<House>();
}