// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WSEA.Data.WSEA;

public partial class Operation
{
    public int IdOperation { get; set; }

    public string Name { get; set; }

    public virtual ICollection<Request> Requests { get; set; } = new List<Request>();
}