// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WSEA.Data.WSEA;

public partial class RealtyTypes
{
    public int IdType { get; set; }

    public string Type { get; set; }

    public virtual ICollection<Realties> Realties { get; set; } = new List<Realties>();
}