// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WSEA.Data.WSEA;

public partial class RealtyImages
{
    public int Id { get; set; }

    public string ImagePath { get; set; }

    public int IdRealty { get; set; }

    public virtual Realties IdRealtyNavigation { get; set; }
}