// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WSEA.Data.WSEA;

public partial class Requests
{
    public int IdRequest { get; set; }

    public DateTime Datetime { get; set; }

    public string Name { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public string Description { get; set; }

    public bool Status { get; set; }

    public int? IdRealtor { get; set; }

    public virtual Realtors IdRealtorNavigation { get; set; }
}